variables:
  CI_IMAGE: $DOCKER_HUB_USER/docker
  CI_TAG: buildx

before_script:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN

build:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  script:
    - docker build -t $CI_IMAGE .
    - docker push $CI_IMAGE
    - docker push $CI_IMAGE:$CI_TAG
  only:
    - master
